# Generated by Django 4.2.6 on 2023-11-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(
                default="uploads/placeholder.txt", upload_to="uploads/"
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="file_type",
            field=models.CharField(default="uploads/placeholder.txt", max_length=10),
            preserve_default=False,
        ),
    ]
