# Generated by Django 4.2.6 on 2023-11-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_uploadedfile_file_uploadedfile_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
