# Generated by Django 5.0 on 2024-01-25 01:15

import app1.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0005_convertedfile_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="convertedfile",
            old_name="original_file",
            new_name="uploaded_file",
        ),
        migrations.RemoveField(
            model_name="convertedfile",
            name="latex_code",
        ),
        migrations.AddField(
            model_name="convertedfile",
            name="file_path",
            field=models.CharField(default="NONE", max_length=255),
        ),
        migrations.AddField(
            model_name="convertedfile",
            name="latex_file",
            field=models.CharField(
                default="/home/acmichelitch/TheBackyardigans/uploads/conversion_output/output.tex",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="convertedfile",
            name="pdf_file",
            field=models.CharField(
                default="/home/acmichelitch/TheBackyardigans/uploads/conversion_output/output.pdf",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(
                blank=True,
                default="placeholder.txt",
                null=True,
                upload_to=app1.models.get_user_subfolder,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["xlsx", "json", "csv", "xls"]
                    )
                ],
            ),
        ),
    ]
