# Generated by Django 5.0 on 2024-01-26 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0005_convertedfile_created_at_convertedfile_file_path_and_more"),
        ("app1", "0006_rename_original_file_convertedfile_uploaded_file_and_more"),
    ]

    operations = []
