# Generated by Django 5.0 on 2024-01-26 20:06

import app1.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0007_merge_20240126_2001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convertedfile",
            name="file_path",
            field=models.CharField(default="NONE", max_length=255),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(
                blank=True,
                default="placeholder.txt",
                null=True,
                upload_to=app1.models.get_user_subfolder,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["xlsx", "json", "csv", "xls"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_path",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
