# Generated by Django 5.0.1 on 2024-01-30 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0008_remove_convertedfile_latex_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="user",
        ),
        migrations.CreateModel(
            name="DefaultStyleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("font_type", models.CharField(default="calibri", max_length=255)),
                ("font_size", models.IntegerField(default="8")),
                ("font_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("wall_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("furniture_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StyleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("font_type", models.CharField(max_length=255)),
                ("font_size", models.IntegerField()),
                ("font_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("wall_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("furniture_color", models.CharField(default="#FFFFFF", max_length=7)),
                (
                    "orientation_type",
                    models.CharField(default="vertical", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="convertedfile",
            name="style_settings",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.stylesettings",
            ),
        ),
        migrations.DeleteModel(
            name="Layout",
        ),
        migrations.DeleteModel(
            name="UserSettings",
        ),
    ]
