# Generated by Django 5.0.1 on 2024-02-05 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0009_remove_usersettings_user_defaultstylesettings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="file_type",
        ),
        migrations.AlterField(
            model_name="convertedfile",
            name="file_name",
            field=models.CharField(default="name", max_length=255),
        ),
        migrations.AlterField(
            model_name="convertedfile",
            name="style_settings",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.stylesettings",
            ),
        ),
        migrations.AlterField(
            model_name="defaultstylesettings",
            name="font_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="defaultstylesettings",
            name="font_type",
            field=models.CharField(default="Arial", max_length=30),
        ),
    ]
