# Generated by Django 5.0.1 on 2024-02-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0010_remove_uploadedfile_file_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaultstylesettings",
            name="door_color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="defaultstylesettings",
            name="door_width",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="defaultstylesettings",
            name="furniture_width",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="defaultstylesettings",
            name="text_decoration",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="defaultstylesettings",
            name="wall_width",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="defaultstylesettings",
            name="window_color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="defaultstylesettings",
            name="window_width",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="door_color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="door_width",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="furniture_width",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="text_decoration",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="wall_width",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="window_color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="window_width",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="defaultstylesettings",
            name="font_size",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="defaultstylesettings",
            name="font_type",
            field=models.CharField(max_length=255),
        ),
    ]
