# Generated by Django 5.0.1 on 2024-02-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0012_convertedfile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stylesettings",
            name="font_type",
            field=models.CharField(
                choices=[
                    ("Default", "Default"),
                    ("Times New Roman", "Times New Roman"),
                    ("Arial", "Arial"),
                ],
                default="Default",
                max_length=56,
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="text_decoration",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("bold", "Bold"),
                    ("underline", "Underline"),
                    ("italics", "Italicize"),
                ],
                default="none",
                max_length=28,
            ),
        ),
    ]
