# Generated by Django 5.0.1 on 2024-02-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0013_alter_stylesettings_font_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convertedfile",
            name="image",
            field=models.CharField(
                default="/home/acmichelitch/TheBackyardigans/layoutGenerator/uploads/conversion_output/output.png",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="convertedfile",
            name="latex_file",
            field=models.CharField(
                default="/home/acmichelitch/TheBackyardigans/layoutGenerator/uploads/conversion_output/output.tex",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="convertedfile",
            name="pdf_file",
            field=models.CharField(
                default="/home/acmichelitch/TheBackyardigans/layoutGenerator/uploads/conversion_output/output.pdf",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="defaultstylesettings",
            name="door_width",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="defaultstylesettings",
            name="font_size",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="defaultstylesettings",
            name="font_type",
            field=models.CharField(
                choices=[
                    ("Default", "Default"),
                    ("Times New Roman", "Times New Roman"),
                    ("Arial", "Arial"),
                ],
                default="Default",
                max_length=56,
            ),
        ),
        migrations.AlterField(
            model_name="defaultstylesettings",
            name="furniture_width",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="defaultstylesettings",
            name="text_decoration",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("bold", "Bold"),
                    ("underline", "Underline"),
                    ("italics", "Italicize"),
                ],
                default="none",
                max_length=28,
            ),
        ),
        migrations.AlterField(
            model_name="defaultstylesettings",
            name="wall_width",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="defaultstylesettings",
            name="window_width",
            field=models.IntegerField(default=2),
        ),
    ]
