# Generated by Django 5.0.1 on 2024-02-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0014_alter_convertedfile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convertedfile",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="convertedfile",
            name="image",
            field=models.CharField(
                default="/home/jmissan_csce311/Desktop/TheBackyardigans/layoutGenerator/uploads/conversion_output/output.png",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="convertedfile",
            name="latex_file",
            field=models.CharField(
                default="/home/jmissan_csce311/Desktop/TheBackyardigans/layoutGenerator/uploads/conversion_output/output.tex",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="convertedfile",
            name="pdf_file",
            field=models.CharField(
                default="/home/jmissan_csce311/Desktop/TheBackyardigans/layoutGenerator/uploads/conversion_output/output.pdf",
                max_length=255,
            ),
        ),
    ]
