# Generated by Django 5.0.2 on 2024-03-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0016_convertedfile_meta_date_convertedfile_meta_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultstylesettings",
            name="font_size",
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="font_color",
            field=models.CharField(default="black", max_length=32),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="font_size",
            field=models.IntegerField(default=12),
        ),
    ]
