# Generated by Django 5.0.2 on 2024-03-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0017_alter_defaultstylesettings_font_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultstylesettings",
            name="font_color",
            field=models.CharField(
                choices=[
                    ("red", "Red"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("cyan", "Cyan"),
                    ("magenta", "Magenta"),
                    ("yellow", "Yellow"),
                    ("black", "Black"),
                    ("gray", "Gray"),
                    ("white", "White"),
                    ("darkgray", "Dark Gray"),
                    ("lightgray", "Light Gray"),
                    ("brown", "Brown"),
                    ("lime", "Lime"),
                    ("olive", "Olive"),
                    ("orange", "Orange"),
                    ("pink", "Pink"),
                    ("purple", "Purple"),
                    ("teal", "Teal"),
                    ("violet", "Violet"),
                ],
                default="black",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="font_color",
            field=models.CharField(
                choices=[
                    ("red", "Red"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("cyan", "Cyan"),
                    ("magenta", "Magenta"),
                    ("yellow", "Yellow"),
                    ("black", "Black"),
                    ("gray", "Gray"),
                    ("white", "White"),
                    ("darkgray", "Dark Gray"),
                    ("lightgray", "Light Gray"),
                    ("brown", "Brown"),
                    ("lime", "Lime"),
                    ("olive", "Olive"),
                    ("orange", "Orange"),
                    ("pink", "Pink"),
                    ("purple", "Purple"),
                    ("teal", "Teal"),
                    ("violet", "Violet"),
                ],
                default="black",
                max_length=32,
            ),
        ),
    ]
