# Generated by Django 5.0.2 on 2024-03-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0019_alter_convertedfile_meta_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convertedfile",
            name="meta_location",
            field=models.TextField(blank=True, default="Address", max_length=256),
        ),
    ]
