# Generated by Django 5.0.2 on 2024-03-11 21:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0020_alter_convertedfile_meta_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convertedfile",
            name="meta_date",
        ),
        migrations.RemoveField(
            model_name="convertedfile",
            name="meta_location",
        ),
        migrations.RemoveField(
            model_name="convertedfile",
            name="meta_title",
        ),
        migrations.RemoveField(
            model_name="defaultstylesettings",
            name="camera_label_text",
        ),
        migrations.RemoveField(
            model_name="defaultstylesettings",
            name="font_size",
        ),
        migrations.RemoveField(
            model_name="defaultstylesettings",
            name="navigation_arrow_label",
        ),
        migrations.RemoveField(
            model_name="defaultstylesettings",
            name="sensor_label_text",
        ),
        migrations.RemoveField(
            model_name="defaultstylesettings",
            name="text_decoration",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="camera_label_text",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="font_size",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="name",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="navigation_arrow_label",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="sensor_label_text",
        ),
        migrations.RemoveField(
            model_name="stylesettings",
            name="text_decoration",
        ),
        migrations.AddField(
            model_name="defaultstylesettings",
            name="calibration_color",
            field=models.CharField(
                choices=[
                    ("red", "Red"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("cyan", "Cyan"),
                    ("magenta", "Magenta"),
                    ("yellow", "Yellow"),
                    ("black", "Black"),
                    ("gray", "Gray"),
                    ("white", "White"),
                    ("darkgray", "Dark Gray"),
                    ("lightgray", "Light Gray"),
                    ("brown", "Brown"),
                    ("lime", "Lime"),
                    ("olive", "Olive"),
                    ("orange", "Orange"),
                    ("pink", "Pink"),
                    ("purple", "Purple"),
                    ("teal", "Teal"),
                    ("violet", "Violet"),
                ],
                default="black",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="calibration_color",
            field=models.CharField(
                choices=[
                    ("red", "Red"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("cyan", "Cyan"),
                    ("magenta", "Magenta"),
                    ("yellow", "Yellow"),
                    ("black", "Black"),
                    ("gray", "Gray"),
                    ("white", "White"),
                    ("darkgray", "Dark Gray"),
                    ("lightgray", "Light Gray"),
                    ("brown", "Brown"),
                    ("lime", "Lime"),
                    ("olive", "Olive"),
                    ("orange", "Orange"),
                    ("pink", "Pink"),
                    ("purple", "Purple"),
                    ("teal", "Teal"),
                    ("violet", "Violet"),
                ],
                default="black",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="meta_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="meta_location",
            field=models.TextField(blank=True, default="Address", max_length=256),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="meta_title",
            field=models.CharField(default="Layout", max_length=64),
        ),
        migrations.AlterField(
            model_name="defaultstylesettings",
            name="font_type",
            field=models.CharField(
                choices=[
                    ("Computer Modern", "Default (Computer Modern)"),
                    ("Times New Roman", "Times New Roman"),
                    ("Arial", "Arial"),
                ],
                default="Computer Modern",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="door_width",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="font_type",
            field=models.CharField(
                choices=[
                    ("Computer Modern", "Default (Computer Modern)"),
                    ("Times New Roman", "Times New Roman"),
                    ("Arial", "Arial"),
                ],
                default="Computer Modern",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="furniture_width",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="wall_width",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="window_width",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="name",
            field=models.CharField(default="name", max_length=64),
        ),
    ]
