# Generated by Django 5.0.2 on 2024-03-22 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0023_alter_stylesettings_user_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stylesettings",
            name="orientation_type",
        ),
        migrations.AddField(
            model_name="stylesettings",
            name="orientation",
            field=models.CharField(
                choices=[("vertical", "Portrait"), ("horizontal", "Landscape")],
                default="vertical",
                max_length=32,
            ),
        ),
    ]
