# Generated by Django 5.0.2 on 2024-03-26 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0024_remove_stylesettings_orientation_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="label",
            name="x_coordinate",
        ),
        migrations.RemoveField(
            model_name="label",
            name="y_coordinate",
        ),
        migrations.AddField(
            model_name="label",
            name="location",
            field=models.CharField(
                choices=[
                    ("above", "Above"),
                    ("below", "Below"),
                    ("left", "Left"),
                    ("right", "Right"),
                ],
                default="above",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="orientation",
            field=models.CharField(
                choices=[("portrait", "Portrait"), ("landscape", "Landscape")],
                default="portrait",
                max_length=32,
            ),
        ),
    ]
