# Generated by Django 5.0.2 on 2024-03-29 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0027_alter_stylesettings_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="type",
            field=models.CharField(default="Sensor", max_length=20),
        ),
    ]
